Fix for issue of sidebar not closing on mobile.
eecs485staff/primer-spec pull request #77
Opened 2020-09-05 03:36 UTC by bjthompson805

Fix for issue #66 to close sidebar if an item is clicked that was already previously selected.

2020-09-05 16:23 UTC, seshrs requested changes
Thanks for the PR, this is awesome! I like your idea of adding a click-handler on the entire table of contents.

One side-effect is that if a user clicks anywhere inside the Table of Contents (even if it's not a link), the Sidebar will close on mobile. However, I think that's a reasonable behavior 😄

2020-09-05 16:23 UTC, seshrs commented on src_js/components/sidebar/TableOfContents.tsx
> +    var sidebarTocListElements : any = document.body.querySelector('aside nav ul.primer-spec-toc-list');
If we're going to add a click-handler, we might as well add it on the entire `<nav>` — in this case, we don't even *need* to use `useEffect()`! Move this logic to an `onClick` attribute of the `<nav>` in the `render()` method.

```jsx
<nav
  id="primer-spec-toc"
  onClick={() => {
    // Move the logic here
  }}
>
  {tocNodes}
</nav>
```

2020-09-05 20:26 UTC, bjthompson805 commented
On this one, I had intended to add it only to the links. I think if the user clicks the sidebar it shouldn't close it until they click a link. What I could do is add it to the <a> tags in the sidebar. What do you think?

2020-09-05 20:50 UTC, seshrs commented
> I think if the user clicks the sidebar it shouldn't close it until they click a link.

Ah I see. I held the same opinion when I first created issue #66. However, it seems unlikely to me that users on small screens would intentionally click/tap the Sidebar (when not scrolling). I also think that they're unlikely to miss the links in the Sidebar while clicking/tapping.

I like that your current approach solves the more annoying issue of the Sidebar not closing when it should 😄 

>  What I could do is add it to the 'a' tags in the sidebar. What do you think?

This could work — I'm concerned about whether adding click-listeners to the `<a>` elements will override the browser-default behavior of scrolling and changing the URL hash. Give it a try, and let me know what you find!

2020-09-06 05:31 UTC, bjthompson805 commented
I tried to simply move the click listener from the `<ul>` to its descendant `<a>` nodes, but it didn't work, so I went with your idea.

I've pushed the changes, where I've moved the logic from useEffect() to an onClick on the `<nav>`.

2020-09-06 20:44 UTC, seshrs approved these changes
This looks great! Thanks again for proposing this fix 😃

2020-09-06 20:44 UTC, merged